import {useState} from 'react';
import type {Business,Review,ReviewInput} from '@/lib/live-store';

export function businessPlace(b:Business){return {id:'business:'+b.id,lat:b.lat,lon:b.lon,tags:{name:b.name,'name:ru':b.name,'atlas:type':'business','atlas:business-id':b.id,'atlas:category':b.category,'addr:street':b.address,phone:b.phone,opening_hours:b.hours}}}
export default function BusinessDetails({business:b,reviews,submitReview}:{business:Business;reviews:Review[];submitReview:(value:ReviewInput)=>Promise<unknown>}){
 const [sending,setSending]=useState(false),[notice,setNotice]=useState(''),[failed,setFailed]=useState(false);
 const approved=reviews.filter(r=>r.businessId===b.id&&r.status==='approved').sort((a,c)=>c.createdAt-a.createdAt);
 const rating=approved.length?(approved.reduce((sum,r)=>sum+r.rating,0)/approved.length).toFixed(1):null;
 async function send(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setSending(true);setNotice('');try{await submitReview({businessId:b.id,name:String(data.get('name')||'').trim(),rating:Number(data.get('rating')),text:String(data.get('text')||'').trim()});setFailed(false);setNotice('Спасибо! Отзыв отправлен на проверку.');form.reset()}catch(error){setFailed(true);setNotice(error instanceof Error?error.message:'Не удалось отправить отзыв')}finally{setSending(false)}}
 return <div className="business-details">{b.info&&<p>{b.info}</p>}{b.email&&<p><a href={'mailto:'+b.email}>{b.email}</a></p>}{b.website&&/^https?:\/\//i.test(b.website)&&<p><a href={b.website} target="_blank" rel="noreferrer">Сайт организации ↗</a></p>}
 {b.menu.length>0&&<details className="business-section"><summary>Меню · {b.menu.length}</summary><div className="business-menu">{b.menu.map(item=><div key={item.id}><span><b>{item.name}</b>{item.description&&<small>{item.description}</small>}</span><strong>{item.price.toLocaleString('ru-RU')} сом.</strong></div>)}</div></details>}
 {b.reviewsEnabled&&<details className="business-section"><summary>Отзывы {rating?`· ★ ${rating} · ${approved.length}`:'· пока нет оценок'}</summary><div className="business-reviews">{approved.slice(0,30).map(r=><article key={r.id}><header><b>{r.name}</b><span aria-label={`${r.rating} из 5`}>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span></header><p>{r.text}</p><small>{new Date(r.createdAt).toLocaleDateString('ru-RU')}</small></article>)}</div><form className="review-form" onSubmit={send}><b>Оставить отзыв</b><label>Ваше имя<input name="name" required maxLength={100} autoComplete="name"/></label><label>Оценка<select name="rating" defaultValue="5">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} из 5</option>)}</select></label><label>Ваш отзыв<textarea name="text" required minLength={1} maxLength={2000} rows={3}/></label><small>Отзывы появляются после проверки администратором.</small><button disabled={sending} type="submit">{sending?'Отправляем…':'Отправить отзыв'}</button>{notice&&<p role={failed?'alert':'status'}>{notice}</p>}</form></details>}
 </div>
}
