import {Worker} from 'node:worker_threads';
export function createRoutingPool(root,{timeoutMs=60000,maxQueue=24}={}) {
 let worker,active=null,serial=0,closed=false,cacheBytes=0;const queue=[],cache=new Map();
 const fail=message=>Object.assign(new Error(message),{status:503});
 function finish(error,result){if(!active)return;clearTimeout(active.timer);const job=active;active=null;if(error)job.reject(error);else{if(!result.error){const bytes=result.routes.reduce((sum,r)=>sum+r.path.length*32,0);const previous=cache.get(job.key);if(previous){cacheBytes-=previous.bytes;cache.delete(job.key)}if(bytes<=16*1024*1024){cache.set(job.key,{value:result,bytes,until:Date.now()+60000});cacheBytes+=bytes}while(cache.size>200||cacheBytes>16*1024*1024){const oldest=cache.keys().next().value;cacheBytes-=cache.get(oldest).bytes;cache.delete(oldest)}}job.resolve(result)}pump()}
 function start(){worker=new Worker(new URL('./routing-thread.mjs',import.meta.url),{workerData:{root}});const current=worker;worker.on('message',message=>{if(current===worker&&message.id===active?.id)finish(null,message)});worker.on('error',()=>{if(current!==worker)return;worker=null;finish(fail('Сервис маршрутов временно недоступен'))});worker.on('exit',()=>{if(current!==worker)return;worker=null;finish(fail('Сервис маршрутов перезапускается'))});worker.unref()}
 function pump(){if(active||closed||!queue.length)return;if(!worker)start();active=queue.shift();active.timer=setTimeout(()=>{const old=worker;worker=null;old?.terminate();finish(fail('Время расчёта маршрута истекло'))},timeoutMs);worker.postMessage({...active.input,id:active.id})}
 return {request(input){if(closed)return Promise.reject(fail('Сервис остановлен'));const key=JSON.stringify(input),hit=cache.get(key);if(hit&&hit.until>Date.now())return Promise.resolve(hit.value);if(queue.length>=maxQueue)return Promise.reject(fail('Сервис занят. Повторите запрос позже'));return new Promise((resolve,reject)=>{queue.push({id:++serial,key,input,resolve,reject});pump()})},close(){closed=true;if(active){clearTimeout(active.timer);active.reject(fail('Сервис остановлен'));active=null}for(const job of queue)job.reject(fail('Сервис остановлен'));queue.length=0;worker?.terminate();worker=null}};
}
