export type Lanes = 0 | 1 | 2 | 3 | 4 | 5 | 6;
export const MAX_LANES: 6;
export function isLanes(value: unknown): value is Lanes;
export function isOneway(tags?: Record<string, string> | null): boolean;
export function totalLanes(asphalt: number, oneway: boolean): number;
export function laneShift(asphalt: number, oneway: boolean): number;
export const ASPHALT_STOPS: readonly (readonly [number, number])[];
export const LANE_METRES: number;
export const SHARED_METRES: number;
export function carriagewayMetres(asphalt: number, oneway: boolean): number;
export function offsetLine(line: number[][], metres: number): number[][];
export function trimLine(line: number[][], metres: number): number[][] | null;
export function ribbon(line: number[][], width: number, caps?: readonly number[]): number[][][][];
export function laneLines(road: LaneRoad, crossing?: (point: number[]) => number): { kind: 'dash' | 'centre'; coordinates: number[][] }[];
export type LaneRoad = { coordinates: number[][]; asphalt: number; oneway?: boolean };
export type LaneIndex = Map<string, { a: number[]; b: number[]; shift: number; half: number }[]>;
export type LaneSpot = { shift: number; half: number };
export function laneSegments(roads: readonly LaneRoad[]): LaneIndex;
export function laneAt(index: LaneIndex, lon: number, lat: number, heading: number, reach?: number): LaneSpot | null;
export type StreetSpot = { bearing: number; half: number };
export function streetAt(index: LaneIndex, lon: number, lat: number, reach?: number): StreetSpot | null;
export function streetCrossings(index: LaneIndex, line: number[][]): (StreetSpot & { point: number[] })[];
export function zebra(point: number[], bearing: number, half: number): number[][][][];
export function lanePieces(index: LaneIndex, path: number[][], keep?: (spot: LaneSpot | null) => number): { shift: number; coordinates: number[][] }[];
