// Places on the map as grey discs with a white pictogram, the name set below. Which pictogram a
// place gets, how important it is when icons crowd, and how big the disc is at each zoom.
// Pure and DOM-free: shared by the map, the page, the glyph generator and the checks.
//
// Pictograms are lucide icon names (see lib/poi-glyphs.mjs, generated by
// scripts/build-poi-glyphs.mjs); `tooth` is drawn by us.

/** Map image ids are this prefix plus the pictogram name, e.g. `poi:utensils`. */
export const POI_IMAGE_PREFIX = 'poi:'
/** CSS pixels across the square image at icon-size 1. */
export const POI_BOX = 32
/** The disc inside the box: centre, outer radius and the width of its white ring. */
export const POI_DISC = { cx: 16, cy: 15.5, outer: 13.5, ring: 1.5 }
export const POI_COLOURS = { disc: '#878d92', ring: '#ffffff', glyph: '#ffffff', shadow: 'rgba(0,0,0,0.28)', label: '#40474d' }
/** CSS pixels across the pictogram at icon-size 1, and its stroke in 24-unit icon space. */
export const POI_GLYPH = { size: 16, stroke: 2.4 }
/** icon-size by zoom: small discs far out, full size from zoom 18. */
export const POI_SIZE_STOPS = [[12, 0.6], [14, 0.72], [16, 0.86], [18, 1]]
export const POI_MINZOOM = 12
/** Pixel size of the name under a disc (the overlay draws it in 600 weight Arial). */
export const POI_LABEL_FONT = 13
/** Far out only the important places show: rank ≤ 1 below zoom 14, ≤ 2 at 14, everything from 15. */
export const POI_RANK_FILTER = ['<=', ['get', 'rank'], ['step', ['zoom'], 1, 14, 2, 15, 9]]

const table = groups => {
  const out = Object.create(null)
  for (const [icon, keys] of Object.entries(groups)) {
    for (const key of keys.split(' ')) {
      if (key in out) throw new Error(`poi-icons: "${key}" is listed twice`)
      out[key] = icon
    }
  }
  return out
}

const AMENITY = table({
  'utensils': 'restaurant food_court',
  'hamburger': 'fast_food',
  'coffee': 'cafe hookah_lounge',
  'monitor': 'internet_cafe',
  'martini': 'bar',
  'beer': 'pub biergarten',
  'disc-3': 'nightclub',
  'ice-cream-cone': 'ice_cream',
  'flame': 'bbq',
  'banknote': 'bank',
  'credit-card': 'atm payment_terminal payment_centre',
  'arrow-left-right': 'bureau_de_change money_transfer',
  'pill': 'pharmacy',
  'hospital': 'hospital',
  'stethoscope': 'clinic doctors',
  'tooth': 'dentist',
  'paw-print': 'veterinary',
  'hand-heart': 'nursing_home social_facility',
  'heart-pulse': 'sanatorium',
  'baby': 'baby_hatch kindergarten childcare',
  'school': 'school prep_school',
  'graduation-cap': 'university college',
  'languages': 'language_school',
  'music': 'music_school',
  'car-front': 'driving_school driver_training',
  'library': 'library',
  'fuel': 'fuel',
  'plug-zap': 'charging_station',
  'square-parking': 'parking parking_entrance',
  'bus-front': 'bus_station',
  'car-taxi-front': 'taxi',
  'droplets': 'car_wash fountain',
  'car': 'car_rental',
  'bike': 'bicycle_rental',
  'ship': 'ferry_terminal',
  'clipboard-check': 'vehicle_inspection',
  'shield': 'police',
  'fire-extinguisher': 'fire_station',
  'building-2': 'townhall public_building',
  'scale': 'courthouse',
  'mail': 'post_office',
  'lock': 'prison',
  'trees': 'ranger_station',
  'users': 'community_centre social_centre events_venue',
  'palette': 'arts_centre',
  'mic': 'studio',
  'drama': 'theatre',
  'clapperboard': 'cinema',
  'dices': 'casino',
  'store': 'marketplace market',
  'shopping-cart': 'supermarket',
  'toilet': 'toilets',
  'glass-water': 'drinking_water',
  'droplet': 'water_point watering_place',
  'bath': 'public_bath',
  'house': 'shelter homes',
  'phone': 'telephone',
  'flower-2': 'grave_yard crematorium',
  'recycle': 'recycling',
  'trash-2': 'waste_disposal',
  'dumbbell': 'dojo',
  'zap': 'energy_company',
})

const SHOP = table({
  'shopping-basket': 'convenience general variety_store kiosk country_store trade wholesale yes',
  'shopping-cart': 'supermarket department_store',
  'shopping-bag': 'mall catalogue bag',
  'shirt': 'clothes fabric curtain sewing',
  'scissors': 'tailor hairdresser',
  'footprints': 'shoes shoe_repair',
  'sparkles': 'beauty cosmetics perfumery',
  'hand': 'massage',
  'wrench': 'car_repair motorcycle_repair car_parts tyres',
  'car': 'car',
  'bike': 'motorcycle bicycle',
  'smartphone': 'mobile_phone',
  'tv': 'electronics appliance',
  'headphones': 'hifi',
  'laptop': 'computer',
  'plug': 'electrical',
  'gamepad-2': 'video_games video anime',
  'sofa': 'furniture interior_decoration carpet',
  'cooking-pot': 'kitchen houseware',
  'bath': 'bathroom_furnishing',
  'hammer': 'doors doityourself hardware',
  'paint-roller': 'paint',
  'palette': 'craft art',
  'croissant': 'bakery',
  'cake-slice': 'pastry',
  'candy': 'confectionery chocolate',
  'apple': 'greengrocer farm',
  'wheat': 'agrarian',
  'beef': 'butcher',
  'fish': 'seafood',
  'milk': 'cheese dairy',
  'sandwich': 'deli',
  'leaf': 'health_food nutrition_supplements',
  'wine': 'alcohol wine',
  'cup-soda': 'beverages',
  'glass-water': 'water',
  'coffee': 'coffee tea',
  'cigarette': 'tobacco',
  'book-open': 'books newsagent',
  'pencil': 'stationery',
  'printer': 'copyshop',
  'camera': 'photo',
  'gift': 'gift',
  'toy-brick': 'toys',
  'baby': 'baby_goods',
  'flower': 'florist',
  'paw-print': 'pet',
  'gem': 'jewelry',
  'watch': 'watches',
  'glasses': 'optician',
  'ear': 'hearing_aids',
  'spray-can': 'chemist',
  'dumbbell': 'sports',
  'tent': 'outdoor hunting',
  'guitar': 'musical_instrument',
  'music': 'music',
  'dices': 'bookmaker',
  'hand-coins': 'pawnbroker money_lender',
  'ticket': 'ticket',
  'plane': 'travel_agency',
  'washing-machine': 'dry_cleaning laundry',
  'flower-2': 'funeral_directors',
})

const TOURISM = table({
  'bed-double': 'hotel motel hostel guest_house apartment',
  'house': 'chalet',
  'mountain-snow': 'alpine_hut wilderness_hut',
  'tent': 'camp_site camp_pitch',
  'caravan': 'caravan_site',
  'trees': 'picnic_site trail_riding_station',
  'landmark': 'museum',
  'image': 'gallery',
  'palette': 'artwork',
  'star': 'attraction',
  'binoculars': 'viewpoint',
  'ferris-wheel': 'theme_park',
  'paw-print': 'zoo',
  'info': 'information',
})

const HISTORIC = table({
  'castle': 'castle fort',
  'pickaxe': 'archaeological_site ruins',
  'landmark': 'memorial monument tomb',
})

const LEISURE = table({
  'volleyball': 'stadium pitch',
  'dumbbell': 'sports_centre fitness_centre',
  'dices': 'bowling_alley',
  'toy-brick': 'playground',
  'trees': 'garden park horse_riding',
})

const HEALTHCARE = table({
  'pill': 'pharmacy',
  'hospital': 'hospital',
  'stethoscope': 'clinic doctor',
  'tooth': 'dentist',
  'flask-conical': 'laboratory sample_collection',
  'droplet': 'blood_donation',
  'baby': 'birthing_centre',
})

/** Businesses published from the admin panel, by their admin category. */
const BUSINESS = table({
  'utensils': 'food',
  'shopping-bag': 'shop',
  'bed-double': 'hotel',
  'stethoscope': 'health',
  'fuel': 'fuel',
  'landmark': 'tourism',
  'briefcase': 'service',
  'building-2': 'other',
})

/** Map objects that are not places of their own: streets, districts, numbered roads, houses. */
const TYPES = table({
  'signpost': 'street',
  'map-pinned': 'district',
  'route': 'route',
  'house': 'house',
  'map-pin': 'label',
})

const RELIGION = table({ 'church': 'christian', 'flame': 'zoroastrian' })

// Lower is more important: sorted first, and kept further out (POI_RANK_FILTER).
const MAJOR = new Set(['hospital', 'graduation-cap', 'bus-front', 'ship', 'store', 'landmark', 'drama', 'clapperboard', 'ferris-wheel', 'castle', 'volleyball', 'building-2', 'library', 'binoculars', 'scale'])
const COMMON = new Set(['utensils', 'coffee', 'hamburger', 'bed-double', 'shopping-cart', 'fuel', 'pill', 'mosque', 'church', 'school', 'banknote', 'mail', 'shield', 'stethoscope', 'tooth', 'star', 'fire-extinguisher', 'paw-print', 'image', 'pickaxe', 'info', 'tent', 'mountain-snow'])
const MINOR = new Set(['credit-card', 'square-parking', 'toilet', 'glass-water', 'droplet', 'phone', 'car-taxi-front', 'arrow-left-right', 'trash-2', 'recycle', 'map-pin', 'house'])

// The tables have no prototype, so a tag value such as `constructor` finds nothing.
const own = (object, key) => typeof key === 'string' ? object[key] : undefined

function iconOf(id, tags) {
  if (id.startsWith('house:')) return 'house'
  if (id.startsWith('point:') || id.startsWith('label:')) return 'map-pin'
  const type = tags['atlas:type']
  if (type === 'business') return own(BUSINESS, tags['atlas:category']) || 'building-2'
  const typed = own(TYPES, type)
  if (typed) return typed
  if (tags.amenity === 'place_of_worship') return own(RELIGION, tags.religion) || 'mosque'
  const historic = own(HISTORIC, tags.historic)
  if (historic && (tags.tourism === 'attraction' || !tags.amenity)) return historic
  const amenity = own(AMENITY, tags.amenity) || own(HEALTHCARE, tags.healthcare)
  if (amenity) return amenity
  if (tags.shop && tags.shop !== 'no') return own(SHOP, tags.shop) || 'shopping-bag'
  return own(TOURISM, tags.tourism) || own(LEISURE, tags.leisure) || (tags.tourism ? 'star' : 'map-pin')
}

/** The pictogram of a place and its rank, 0 (always shown) to 4 (only close in). */
export function poiStyle(id, tags) {
  const safe = tags || {}, icon = iconOf(String(id || ''), safe), type = safe['atlas:type']
  const rank = type === 'business' ? 0
    : type === 'landmark' || type === 'route' || safe.shop === 'mall' || safe.shop === 'department_store' || MAJOR.has(icon) ? 1
    : safe.amenity === 'shelter' || MINOR.has(icon) ? 4
    : COMMON.has(icon) ? 2 : 3
  return { icon, rank }
}

/**
 * The places to put on the map around a centre: the `limit` nearest, then up to `majors` more of
 * the nearest important ones (rank ≤ 1), so a zoomed-out view still shows hospitals, markets and
 * museums across the screen rather than only the few inside the nearest cluster.
 */
export function poiNearby(places, lon, lat, limit = 300, majors = 100) {
  const cos = Math.cos(lat * Math.PI / 180)
  const sorted = places.map(place => ({ place, gap: Math.hypot(place.lat - lat, (place.lon - lon) * cos) }))
    .sort((a, b) => a.gap - b.gap)
  const out = sorted.slice(0, limit).map(item => item.place)
  for (let i = limit, extra = 0; i < sorted.length && extra < majors; i++) {
    const place = sorted[i].place
    if (rankOf(place) <= 1) { out.push(place); extra++ }
  }
  return out
}

// A place object's rank, worked out once: the page hands the same objects over on every map move.
const ranks = new WeakMap()
function rankOf(place) {
  let rank = ranks.get(place)
  if (rank === undefined) ranks.set(place, rank = poiStyle(place.id, place.tags).rank)
  return rank
}

/** Every pictogram poiStyle can return, sorted: the list the glyph generator draws. */
export const POI_ICON_NAMES = [...new Set([
  ...[AMENITY, SHOP, TOURISM, HISTORIC, LEISURE, HEALTHCARE, BUSINESS, TYPES, RELIGION].flatMap(Object.values),
  'mosque', 'shopping-bag', 'star', 'map-pin', 'building-2',
])].sort()

/** icon-size at a zoom: linear between POI_SIZE_STOPS, held at the ends. */
export function poiIconScale(zoom) {
  const stops = POI_SIZE_STOPS
  if (!(zoom > stops[0][0])) return stops[0][1]
  for (let i = 1; i < stops.length; i++) {
    const [z1, s1] = stops[i]
    if (zoom <= z1) {
      const [z0, s0] = stops[i - 1]
      return s0 + (s1 - s0) * (zoom - z0) / (z1 - z0)
    }
  }
  return stops[stops.length - 1][1]
}

/** CSS pixels from a place's point to the edge of its disc. */
export const poiRadius = zoom => poiIconScale(zoom) * POI_DISC.outer

/** CSS pixels from a place's point down to the middle of its name: under the disc, a 2 px gap. */
export const poiLabelOffset = zoom => poiIconScale(zoom) * (POI_DISC.cy - POI_BOX / 2 + POI_DISC.outer) + 2 + POI_LABEL_FONT / 2

/** The MapLibre icon-size expression matching poiIconScale. */
export const poiIconSizeExpression = () => ['interpolate', ['linear'], ['zoom'], ...POI_SIZE_STOPS.flat()]
