/** SVG path data of one pictogram in a 24×24 box: `s` paths are stroked, `f` paths filled and stroked. */
export type Glyph = { readonly s: readonly string[]; readonly f?: readonly string[] }
/** Where the paths came from, e.g. `lucide-react 1.31.0`. */
export const GLYPH_SOURCE: string
/** Pictograms by lucide icon name (plus `tooth`), generated by scripts/build-poi-glyphs.mjs. */
export const GLYPHS: Readonly<Record<string, Glyph | undefined>>
